### ISSUE TITLE
only accept links for documents...

### ISSUE THREAD

**Issue by johnfelipe** [sorensenjg/wp-doc-viewer#2]
i need to know if only accept URL or links, or can i upload via wordpress and via shortcode or something have a preview of all document
Stay alert

**Comment by sorensenjg** [comment]
This currently only accepts urls. I will be providing a shortcode in the future that will tap directly into the wordpress media library, as well as, accept any external url. Stay tuned..

**Comment by sorensenjg** [comment]
Opened an issue for the addition of a shortcode. See issue #3
